modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="aquatech_ui"
version="1.0.27"
displayName="AquaTech Ocean UI"
authors="AquaTech"
description='''Ocean-themed LoliLand-style UI: custom Tab, HUD, nametags and chat bubbles for AquaTech.'''

[[dependencies.aquatech_ui]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aquatech_ui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aquatech_ui]]
    modId="luckperms"
    mandatory=false
    versionRange="[5.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.aquatech_ui]]
    modId="mcef"
    mandatory=false
    versionRange="[2.1,)"
    ordering="AFTER"
    side="CLIENT"

