package net.aquatech.machines.util;

// GENERATED by tools/build_machine_guis.py. Do not edit by hand: change the script and rerun it.

/** Раскладка GUI механизмов: размеры, слоты (левый верх предмета 16x16) и прямоугольники динамики. */
public final class MachineLayout {

    public static final int IMAGE_W = 256;
    public static final int IMAGE_H = 212;
    public static final int ATLAS_Y = 214;
    public static final int PLAYER_X = 47;
    public static final int PLAYER_Y = 131;
    public static final int HOTBAR_Y = 189;
    public static final int ENERGY_X = 28;
    public static final int ENERGY_Y = 99;
    public static final int ENERGY_W = 180;
    public static final int ENERGY_H = 6;
    public static final int BAR2_X = 28;
    public static final int BAR2_Y = 110;
    public static final int BAR2_W = 180;
    public static final int BAR2_H = 6;
    public static final int UPG_X = 220;
    public static final int UPG_SPEED_Y = 29;
    public static final int UPG_BATTERY_Y = 53;
    public static final int UPG_EFF_Y = 77;
    public static final int PLAQUE_CENTER_X = 127;
    public static final int PLAQUE_TEXT_Y = 7;

    private MachineLayout() {
    }

    // Рыболов MK-1
    public static final int FISHER_MK1_ROD_X = 34;
    public static final int FISHER_MK1_ROD_Y = 34;
    public static final int FISHER_MK1_BATTERY_X = 34;
    public static final int FISHER_MK1_BATTERY_Y = 62;
    public static final int FISHER_MK1_OUTPUT_X = 190;
    public static final int FISHER_MK1_OUTPUT_Y = 48;
    public static final int FISHER_MK1_POND_X = 72;
    public static final int FISHER_MK1_POND_Y = 28;
    public static final int FISHER_MK1_POND_W = 96;
    public static final int FISHER_MK1_POND_H = 60;

    // Авто-Рыболов MK-2
    public static final int FISHER_ROD_X = 34;
    public static final int FISHER_ROD_Y = 34;
    public static final int FISHER_CORE_X = 34;
    public static final int FISHER_CORE_Y = 62;
    public static final int FISHER_OUTPUT_X = 190;
    public static final int FISHER_OUTPUT_Y = 48;
    public static final int FISHER_POND_X = 72;
    public static final int FISHER_POND_Y = 28;
    public static final int FISHER_POND_W = 96;
    public static final int FISHER_POND_H = 60;

    // Экстрактор
    public static final int EXTRACTOR_INPUT_X = 62;
    public static final int EXTRACTOR_INPUT_Y = 49;
    public static final int EXTRACTOR_OUTPUT_X = 140;
    public static final int EXTRACTOR_OUTPUT_Y = 49;
    public static final int EXTRACTOR_ARROW_X = 96;
    public static final int EXTRACTOR_ARROW_Y = 50;
    public static final int EXTRACTOR_ARROW_W = 24;
    public static final int EXTRACTOR_ARROW_H = 17;

    // Экскаватор
    public static final int EXCAVATOR_OUT0_X = 112;
    public static final int EXCAVATOR_OUT0_Y = 30;
    public static final int EXCAVATOR_OUT1_X = 130;
    public static final int EXCAVATOR_OUT1_Y = 30;
    public static final int EXCAVATOR_OUT2_X = 148;
    public static final int EXCAVATOR_OUT2_Y = 30;
    public static final int EXCAVATOR_OUT3_X = 112;
    public static final int EXCAVATOR_OUT3_Y = 48;
    public static final int EXCAVATOR_OUT4_X = 130;
    public static final int EXCAVATOR_OUT4_Y = 48;
    public static final int EXCAVATOR_OUT5_X = 148;
    public static final int EXCAVATOR_OUT5_Y = 48;
    public static final int EXCAVATOR_OUT6_X = 112;
    public static final int EXCAVATOR_OUT6_Y = 66;
    public static final int EXCAVATOR_OUT7_X = 130;
    public static final int EXCAVATOR_OUT7_Y = 66;
    public static final int EXCAVATOR_OUT8_X = 148;
    public static final int EXCAVATOR_OUT8_Y = 66;
    public static final int EXCAVATOR_ARROW_X = 70;
    public static final int EXCAVATOR_ARROW_Y = 50;
    public static final int EXCAVATOR_ARROW_W = 24;
    public static final int EXCAVATOR_ARROW_H = 17;

    // Центрифуга
    public static final int CENTRIFUGE_RAW_IN_X = 52;
    public static final int CENTRIFUGE_RAW_IN_Y = 34;
    public static final int CENTRIFUGE_RAW_OUT_X = 52;
    public static final int CENTRIFUGE_RAW_OUT_Y = 62;
    public static final int CENTRIFUGE_DISTILL_EMPTY_X = 164;
    public static final int CENTRIFUGE_DISTILL_EMPTY_Y = 34;
    public static final int CENTRIFUGE_DISTILL_FULL_X = 164;
    public static final int CENTRIFUGE_DISTILL_FULL_Y = 62;
    public static final int CENTRIFUGE_MINERAL0_X = 112;
    public static final int CENTRIFUGE_MINERAL0_Y = 36;
    public static final int CENTRIFUGE_MINERAL1_X = 130;
    public static final int CENTRIFUGE_MINERAL1_Y = 36;
    public static final int CENTRIFUGE_MINERAL2_X = 112;
    public static final int CENTRIFUGE_MINERAL2_Y = 54;
    public static final int CENTRIFUGE_MINERAL3_X = 130;
    public static final int CENTRIFUGE_MINERAL3_Y = 54;
    public static final int CENTRIFUGE_TANK_RAW_X = 30;
    public static final int CENTRIFUGE_TANK_RAW_Y = 28;
    public static final int CENTRIFUGE_TANK_RAW_W = 12;
    public static final int CENTRIFUGE_TANK_RAW_H = 58;
    public static final int CENTRIFUGE_TANK_DIST_X = 190;
    public static final int CENTRIFUGE_TANK_DIST_Y = 28;
    public static final int CENTRIFUGE_TANK_DIST_W = 12;
    public static final int CENTRIFUGE_TANK_DIST_H = 58;
    public static final int CENTRIFUGE_ARROW_X = 80;
    public static final int CENTRIFUGE_ARROW_Y = 50;
    public static final int CENTRIFUGE_ARROW_W = 24;
    public static final int CENTRIFUGE_ARROW_H = 17;

    // Гидротермальный синтезатор
    public static final int SYNTHESIZER_FLUID_IN_X = 52;
    public static final int SYNTHESIZER_FLUID_IN_Y = 34;
    public static final int SYNTHESIZER_FLUID_OUT_X = 52;
    public static final int SYNTHESIZER_FLUID_OUT_Y = 62;
    public static final int SYNTHESIZER_INPUT_A_X = 84;
    public static final int SYNTHESIZER_INPUT_A_Y = 34;
    public static final int SYNTHESIZER_INPUT_B_X = 84;
    public static final int SYNTHESIZER_INPUT_B_Y = 62;
    public static final int SYNTHESIZER_OUTPUT1_X = 146;
    public static final int SYNTHESIZER_OUTPUT1_Y = 34;
    public static final int SYNTHESIZER_OUTPUT2_X = 146;
    public static final int SYNTHESIZER_OUTPUT2_Y = 62;
    public static final int SYNTHESIZER_OUTPUT3_X = 178;
    public static final int SYNTHESIZER_OUTPUT3_Y = 48;
    public static final int SYNTHESIZER_TANK_LAVA_X = 30;
    public static final int SYNTHESIZER_TANK_LAVA_Y = 28;
    public static final int SYNTHESIZER_TANK_LAVA_W = 12;
    public static final int SYNTHESIZER_TANK_LAVA_H = 58;
    public static final int SYNTHESIZER_ARROW_X = 108;
    public static final int SYNTHESIZER_ARROW_Y = 50;
    public static final int SYNTHESIZER_ARROW_W = 24;
    public static final int SYNTHESIZER_ARROW_H = 17;

    // Цветолов
    public static final int FLOWER_COLLECTOR_OUT1_X = 112;
    public static final int FLOWER_COLLECTOR_OUT1_Y = 50;
    public static final int FLOWER_COLLECTOR_OUT2_X = 130;
    public static final int FLOWER_COLLECTOR_OUT2_Y = 50;
    public static final int FLOWER_COLLECTOR_OUT3_X = 148;
    public static final int FLOWER_COLLECTOR_OUT3_Y = 50;
    public static final int FLOWER_COLLECTOR_ARROW_X = 66;
    public static final int FLOWER_COLLECTOR_ARROW_Y = 50;
    public static final int FLOWER_COLLECTOR_ARROW_W = 24;
    public static final int FLOWER_COLLECTOR_ARROW_H = 17;

    // Мана-Фабрикатор
    public static final int MANA_FABRICATOR_ARROW_X = 70;
    public static final int MANA_FABRICATOR_ARROW_Y = 50;
    public static final int MANA_FABRICATOR_ARROW_W = 24;
    public static final int MANA_FABRICATOR_ARROW_H = 17;
    public static final int MANA_FABRICATOR_CRYSTAL_X = 110;
    public static final int MANA_FABRICATOR_CRYSTAL_Y = 32;
    public static final int MANA_FABRICATOR_CRYSTAL_W = 48;
    public static final int MANA_FABRICATOR_CRYSTAL_H = 48;

    // Рыбный генератор
    public static final int FISH_GENERATOR_FUEL_X = 46;
    public static final int FISH_GENERATOR_FUEL_Y = 48;
    public static final int FISH_GENERATOR_FLAMES_X = 92;
    public static final int FISH_GENERATOR_FLAMES_Y = 30;
    public static final int FISH_GENERATOR_FLAMES_W = 80;
    public static final int FISH_GENERATOR_FLAMES_H = 56;

}
