// Rename StarCatcher rods to clear progressive Resource Rod Tiers
ClientEvents.lang('ru_ru', event => {
  event.add('item.starcatcher.bamboo_rod', 'Ресурсная удочка I ур. (Бамбуковая)')
  event.add('item.starcatcher.humble_rod', 'Ресурсная удочка II ур. (Скромная)')
  event.add('item.starcatcher.good_old_rod', 'Ресурсная удочка III ур. (Старая добрая)')
  event.add('item.starcatcher.naturalist_rod', 'Ресурсная удочка IV ур. (Натуралиста)')
  event.add('item.starcatcher.slimed_rod', 'Ресурсная удочка V ур. (Слизневая)')
  event.add('item.starcatcher.iceborn_rod', 'Ресурсная удочка VI ур. (Ледяная)')
  event.add('item.starcatcher.starcatcher_rod', 'Ресурсная удочка VII ур. (Ловец Звёзд)')
  event.add('item.starcatcher.azure_crystal_rod', 'Ресурсная удочка VIII ур. (Лазурный кристалл)')
  event.add('item.starcatcher.sharktooth_rod', 'Ресурсная удочка IX ур. (Акулий клык)')
  event.add('item.starcatcher.obsidian_rod', 'Ресурсная удочка X ур. (Обсидиановая)')
  event.add('item.starcatcher.lush_glowberry_rod', 'Ресурсная удочка XI ур. (Светящаяся ягода)')
  event.add('item.starcatcher.magmaforged_rod', 'Ресурсная удочка XII ур. (Магматическая)')
  event.add('item.starcatcher.boner_rod', 'Костяная удочка (мобы)')
  event.add('item.starcatcher.sky_rod', 'Небесная удочка (рыба)')
})
