package net.aquatech.ui.client;

import java.util.HashMap;
import java.util.Map;

// GENERATED by tools/build_rod_drop_table.py from FishingLootHandler. Do not edit by hand.

/** С каких удочек падает ресурс: тиры 1..13, 100 это костяная удочка, 101 небесная. */
final class RodDropTable {

    static final int BONER = 100;
    static final int SKY = 101;
    private static final Map<String, int[]> TIERS = new HashMap<>();

    static {
        TIERS.put("ae2:certus_quartz_crystal", new int[]{101});
        TIERS.put("ae2:charged_certus_quartz_crystal", new int[]{101});
        TIERS.put("ae2:fluix_crystal", new int[]{101});
        TIERS.put("ae2:sky_dust", new int[]{101});
        TIERS.put("ae2:sky_stone_block", new int[]{101});
        TIERS.put("industrialupgrade:alloyingot/inconel", new int[]{11, 12});
        TIERS.put("industrialupgrade:alloyingot/osmiridium", new int[]{12, 13});
        TIERS.put("industrialupgrade:alloyingot/stainless_steel", new int[]{9, 10});
        TIERS.put("industrialupgrade:asteroidore/asteroid_adamantium_ore", new int[]{12, 13});
        TIERS.put("industrialupgrade:baseore/aluminium", new int[]{5, 6});
        TIERS.put("industrialupgrade:baseore/chromium", new int[]{5, 6, 7});
        TIERS.put("industrialupgrade:baseore/cobalt", new int[]{8, 9});
        TIERS.put("industrialupgrade:baseore/germanium", new int[]{8});
        TIERS.put("industrialupgrade:baseore/iridium", new int[]{6, 13});
        TIERS.put("industrialupgrade:baseore/magnesium", new int[]{4});
        TIERS.put("industrialupgrade:baseore/manganese", new int[]{9});
        TIERS.put("industrialupgrade:baseore/mikhail", new int[]{8});
        TIERS.put("industrialupgrade:baseore/nickel", new int[]{5, 9});
        TIERS.put("industrialupgrade:baseore/niobium", new int[]{9});
        TIERS.put("industrialupgrade:baseore/platinum", new int[]{10, 11});
        TIERS.put("industrialupgrade:baseore/silver", new int[]{5, 6});
        TIERS.put("industrialupgrade:baseore/spinel", new int[]{3});
        TIERS.put("industrialupgrade:baseore/sulfur", new int[]{8});
        TIERS.put("industrialupgrade:baseore/titanium", new int[]{2, 8, 9, 10});
        TIERS.put("industrialupgrade:baseore/tungsten", new int[]{6, 7});
        TIERS.put("industrialupgrade:baseore/zinc", new int[]{6});
        TIERS.put("industrialupgrade:baseore/zirconium", new int[]{9});
        TIERS.put("industrialupgrade:baseore1/osmium", new int[]{13});
        TIERS.put("industrialupgrade:baseore2/arsenic", new int[]{5});
        TIERS.put("industrialupgrade:baseore2/barium", new int[]{4, 5});
        TIERS.put("industrialupgrade:baseore2/bismuth", new int[]{6});
        TIERS.put("industrialupgrade:baseore2/polonium", new int[]{5, 13});
        TIERS.put("industrialupgrade:baseore2/strontium", new int[]{3, 4, 5});
        TIERS.put("industrialupgrade:baseore2/thallium", new int[]{3});
        TIERS.put("industrialupgrade:baseore2/yttrium", new int[]{3});
        TIERS.put("industrialupgrade:blockpreciousore/sapphire_ore", new int[]{8});
        TIERS.put("industrialupgrade:blockresource/untreated_peat", new int[]{1});
        TIERS.put("industrialupgrade:calcium_phosphate", new int[]{5});
        TIERS.put("industrialupgrade:classicore/lead", new int[]{7});
        TIERS.put("industrialupgrade:classicore/tin", new int[]{1, 2, 3, 4});
        TIERS.put("industrialupgrade:crafting_elements/crafting_476_element", new int[]{5});
        TIERS.put("industrialupgrade:crushed/uranium", new int[]{11, 12});
        TIERS.put("industrialupgrade:fluorapatite", new int[]{5});
        TIERS.put("industrialupgrade:helium", new int[]{5});
        TIERS.put("industrialupgrade:mineral/crystal", new int[]{7, 8});
        TIERS.put("industrialupgrade:preciousgem/ruby_gem", new int[]{9});
        TIERS.put("industrialupgrade:preciousgem/sapphire_gem", new int[]{6, 7, 8});
        TIERS.put("industrialupgrade:preciousgem/topaz_gem", new int[]{6, 7, 8});
        TIERS.put("industrialupgrade:raw_latex", new int[]{1});
        TIERS.put("industrialupgrade:sapling/rubber_sapling", new int[]{1});
        TIERS.put("minecraft:amethyst_shard", new int[]{8});
        TIERS.put("minecraft:arrow", new int[]{100});
        TIERS.put("minecraft:bamboo", new int[]{1});
        TIERS.put("minecraft:beetroot_seeds", new int[]{5});
        TIERS.put("minecraft:birch_sapling", new int[]{1});
        TIERS.put("minecraft:bone", new int[]{100});
        TIERS.put("minecraft:carrot", new int[]{5, 100});
        TIERS.put("minecraft:clay_ball", new int[]{1, 2});
        TIERS.put("minecraft:coal_ore", new int[]{2});
        TIERS.put("minecraft:cobblestone", new int[]{1, 2});
        TIERS.put("minecraft:cobweb", new int[]{100});
        TIERS.put("minecraft:copper_ingot", new int[]{100});
        TIERS.put("minecraft:copper_ore", new int[]{1, 2});
        TIERS.put("minecraft:crying_obsidian", new int[]{9});
        TIERS.put("minecraft:diamond", new int[]{3, 4, 5, 8, 9, 10});
        TIERS.put("minecraft:diamond_block", new int[]{4, 5, 6, 9});
        TIERS.put("minecraft:dirt", new int[]{1});
        TIERS.put("minecraft:emerald", new int[]{100});
        TIERS.put("minecraft:ender_pearl", new int[]{100});
        TIERS.put("minecraft:feather", new int[]{3});
        TIERS.put("minecraft:glass_bottle", new int[]{100});
        TIERS.put("minecraft:glowstone_dust", new int[]{100});
        TIERS.put("minecraft:gold_ore", new int[]{6, 7});
        TIERS.put("minecraft:gravel", new int[]{1});
        TIERS.put("minecraft:gunpowder", new int[]{100});
        TIERS.put("minecraft:heart_of_the_sea", new int[]{10, 11});
        TIERS.put("minecraft:iron_ingot", new int[]{100});
        TIERS.put("minecraft:iron_ore", new int[]{2, 3, 4, 6});
        TIERS.put("minecraft:lapis_lazuli", new int[]{7, 8});
        TIERS.put("minecraft:lapis_ore", new int[]{3, 7, 8});
        TIERS.put("minecraft:lead", new int[]{5});
        TIERS.put("minecraft:leather", new int[]{5});
        TIERS.put("minecraft:melon_seeds", new int[]{5});
        TIERS.put("minecraft:nether_star", new int[]{11, 12, 13});
        TIERS.put("minecraft:netherite_ingot", new int[]{11});
        TIERS.put("minecraft:netherite_scrap", new int[]{8, 11, 12});
        TIERS.put("minecraft:oak_sapling", new int[]{1});
        TIERS.put("minecraft:obsidian", new int[]{5, 9, 10});
        TIERS.put("minecraft:phantom_membrane", new int[]{100});
        TIERS.put("minecraft:potato", new int[]{5, 100});
        TIERS.put("minecraft:prismarine_crystals", new int[]{10, 11, 100});
        TIERS.put("minecraft:prismarine_shard", new int[]{10, 11, 100});
        TIERS.put("minecraft:pumpkin_seeds", new int[]{5});
        TIERS.put("minecraft:quartz", new int[]{12, 101});
        TIERS.put("minecraft:redstone", new int[]{100});
        TIERS.put("minecraft:redstone_ore", new int[]{3});
        TIERS.put("minecraft:rotten_flesh", new int[]{100});
        TIERS.put("minecraft:saddle", new int[]{100});
        TIERS.put("minecraft:sand", new int[]{1});
        TIERS.put("minecraft:sea_lantern", new int[]{10});
        TIERS.put("minecraft:slime_ball", new int[]{1, 100});
        TIERS.put("minecraft:slime_block", new int[]{4});
        TIERS.put("minecraft:snow_block", new int[]{100});
        TIERS.put("minecraft:snowball", new int[]{100});
        TIERS.put("minecraft:spider_eye", new int[]{100});
        TIERS.put("minecraft:stick", new int[]{100});
        TIERS.put("minecraft:string", new int[]{1, 100});
        TIERS.put("minecraft:sugar", new int[]{100});
        TIERS.put("minecraft:sugar_cane", new int[]{5});
        TIERS.put("minecraft:totem_of_undying", new int[]{100});
        TIERS.put("minecraft:wheat_seeds", new int[]{5});
        TIERS.put("minecraft:white_wool", new int[]{5});
    }

    private RodDropTable() {
    }

    /** Отсортированные тиры или null, если предмет с удочек не падает. */
    static int[] tiersOf(String itemId) {
        return TIERS.get(itemId);
    }
}
