#!/usr/bin/env python3
"""Build (and optionally apply) LuckPerms rank groups matching the aquatech-ui rank glyphs.

Glyph chars are read from ranks.json provider order (U+E100..U+E113); priorities come from
RANKS_SPEC in tools/build_all_rank_badges.py. Live LP runs on MySQL - this script only emits
console commands, it never touches a database.

Dry-run (default) writes tools/server_setup/lp_rank_commands.txt.
Apply sends each command through scripts/tasks/apex_console_ops.py --cmd.

Examples:
  python tools/server_setup/apply_lp_rank_groups.py
  python tools/server_setup/apply_lp_rank_groups.py --apply
"""
from __future__ import annotations

import argparse
import ast
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BUILD_ALL = ROOT / "tools" / "build_all_rank_badges.py"
RANKS_JSON = (
    ROOT
    / "mods"
    / "aquatech-ui"
    / "src"
    / "main"
    / "resources"
    / "assets"
    / "aquatech_ui"
    / "font"
    / "ranks.json"
)
GLYPH_PROPS = ROOT / "server" / "config" / "aquatech_rank_glyphs.properties"
CONSOLE_OPS = ROOT / "scripts" / "tasks" / "apex_console_ops.py"
OUT_FILE = ROOT / "tools" / "server_setup" / "lp_rank_commands.txt"

# Groups that must not inherit default. Mirrors RANKS_SPEC's exclusion of owner/admin/npc,
# minus npc: the group list here is the rank list, npc still inherits default per spec.
NO_DEFAULT_PARENT = {"default", "owner", "admin"}

HEADER = (
    "# LuckPerms rank groups for aquatech-ui rank glyphs (PUA U+E100..U+E113)",
    "# Generated by tools/server_setup/apply_lp_rank_groups.py (dry-run)",
    "# Apply with: python tools/server_setup/apply_lp_rank_groups.py --apply",
    "#",
    "# Permission intent in tools/build_all_rank_badges.py (yaml-storage branch), NOT applied here:",
    "#   owner   -> permissions: [\"- '*'\"]  (wildcard; grant by hand if wanted)",
    "#   default -> essentials.spawn, ftbquests.open",
    "#   that builder also skips the default parent for owner/admin/npc",
    "# Re-running is safe: lp creategroup on an existing group answers \"already exists\".",
)


def ranks_spec() -> list[tuple[str, int]]:
    tree = ast.parse(BUILD_ALL.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "RANKS_SPEC" for target in node.targets
        ):
            rows = ast.literal_eval(node.value)
            return [(str(stem), int(prio)) for stem, _group, prio, _text, _col in rows]
    raise SystemExit(f"RANKS_SPEC not found in {BUILD_ALL}")


def glyph_map() -> dict[str, str]:
    data = json.loads(RANKS_JSON.read_text(encoding="utf-8"))
    glyphs: dict[str, str] = {}
    for provider in data.get("providers", []):
        if provider.get("type") == "bitmap":
            glyphs[Path(provider["file"]).stem] = provider["chars"][0]
    return glyphs


def rank_rows() -> list[tuple[str, str, int]]:
    spec = ranks_spec()
    glyphs = glyph_map()
    spec_stems = [stem for stem, _prio in spec]
    if len(glyphs) != len(spec_stems) or set(glyphs) != set(spec_stems):
        raise SystemExit(
            "ranks.json providers do not match RANKS_SPEC stems:\n"
            f"  spec : {spec_stems}\n"
            f"  glyph: {sorted(glyphs)}"
        )
    prio_by_stem = dict(spec)
    total = len(spec_stems)
    rows: list[tuple[str, str, int]] = []
    for index, stem in enumerate(spec_stems):
        priority = prio_by_stem.get(stem)
        if priority is None:
            priority = total - index  # owner highest when RANKS_SPEC has no entry
        rows.append((stem, glyphs[stem], priority))
    return rows


def build_commands(rows: list[tuple[str, str, int]]) -> list[str]:
    commands: list[str] = list(HEADER)
    commands.append("")
    commands.append("# --- groups ---")
    for group, _glyph, _prio in rows:
        commands.append(f"lp creategroup {group}")
    commands.append("")
    commands.append("# --- prefixes (glyph + trailing space) ---")
    for group, glyph, _prio in rows:
        commands.append(f'lp group {group} meta setprefix "{glyph} "')
    commands.append("")
    commands.append("# --- weights (RANKS_SPEC priority) ---")
    for group, _glyph, prio in rows:
        commands.append(f"lp group {group} meta setweight {prio}")
    commands.append("")
    commands.append("# --- parents ---")
    for group, _glyph, _prio in rows:
        if group not in NO_DEFAULT_PARENT:
            commands.append(f"lp group {group} parent add default")
    commands.append("lp group admin parent add owner")
    return commands


def visible(commands: list[str]) -> list[str]:
    return [c for c in commands if c and not c.startswith("#")]


def write_commands_file(commands: list[str]) -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(commands) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_FILE} ({len(visible(commands))} commands)")


def print_summary(rows: list[tuple[str, str, int]]) -> None:
    print(f"{'group':<10} {'glyph':<6} {'prio':>4}")
    print(f"{'-' * 10} {'-' * 6} {'-' * 4}")
    for group, glyph, prio in rows:
        print(f"{group:<10} U+{ord(glyph):04X} {prio:>4}")
    print(f"{len(rows)} groups")


def console_call(cmd: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CONSOLE_OPS), "--cmd", cmd],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )


def ascii_safe(text: str) -> str:
    # Windows consoles here are cp1251/cp866; PUA glyphs would crash print() mid-apply.
    return text.encode("ascii", "backslashreplace").decode("ascii")


def panel_refuses(result: subprocess.CompletedProcess[str]) -> str:
    blob = f"{result.stdout}\n{result.stderr}".lower()
    if "409" in blob or "suspended" in blob:
        return "panel returned 409/suspended"
    if "fail panel state=" in blob:
        return "server is not running"
    return "console helper failed"


def apply_commands(commands: list[str]) -> int:
    if not CONSOLE_OPS.is_file():
        print(f"ABORT: missing console helper {CONSOLE_OPS}", file=sys.stderr)
        return 2
    probe = console_call("list")
    if probe.returncode != 0:
        print(f"ABORT: {panel_refuses(probe)}. Nothing was applied; dry-run file kept.", file=sys.stderr)
        print(ascii_safe((probe.stderr or probe.stdout).strip()), file=sys.stderr)
        return 2
    todo = visible(commands)
    for index, cmd in enumerate(todo, start=1):
        result = console_call(cmd)
        if result.returncode != 0:
            print(
                f"ABORT at {index}/{len(todo)}: {panel_refuses(result)}\n"
                f"  command: {ascii_safe(cmd)}\n"
                f"  dry-run file kept: {OUT_FILE}",
                file=sys.stderr,
            )
            print(ascii_safe((result.stderr or result.stdout).strip()), file=sys.stderr)
            return 1
        print(f"[{index}/{len(todo)}] {ascii_safe(cmd)}")
    print(f"Applied {len(todo)} commands.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply LuckPerms rank groups for aquatech-ui glyphs")
    parser.add_argument("--apply", action="store_true", help="Send commands to the live panel (default: dry-run)")
    parser.add_argument("--dry-run", action="store_true", help="Explicit dry-run (the default)")
    args = parser.parse_args()
    if args.apply and args.dry_run:
        parser.error("--apply and --dry-run are mutually exclusive")

    rows = rank_rows()
    commands = build_commands(rows)
    print_summary(rows)
    write_commands_file(commands)
    print("Rank glyphs source:", GLYPH_PROPS.relative_to(ROOT))
    if not args.apply:
        print("Dry-run only. Re-run with --apply when the server is up.")
        return 0
    return apply_commands(commands)


if __name__ == "__main__":
    raise SystemExit(main())
