#Minecraft server properties
#Sat Aug 08 12:13:41 MSK 2026
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
debug=false
difficulty=hard
enable-command-block=true
enable-jmx-monitoring=false
enable-query=true
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla,file/aquatech_deep_ocean,file/aquatech_spawn_raft,file/aquatech_rare_ores,file/aquatech_water_pressure,file/aquatech_ocean_life,file/aquatech_resource_rods
level-name=world
level-seed=
level-type=minecraft\:normal
max-chained-neighbor-updates=1000000
max-players=50
max-tick-time=60000
max-world-size=29999984
motd=§b§lAquaTech New Horizont §8| §7FTB Quests §8· §7Beta
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=15
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
require-resource-pack=false
resource-pack=
resource-pack-prompt=§bAquaTech §7— New Horizont
resource-pack-sha1=34da0c1c38dc812e12875dccebd127a6cdcfc469
server-ip=
server-name=AquaTech New Horizont
server-port=25565
simulation-distance=5
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=false
text-filtering-config=
use-native-transport=true
view-distance=6
white-list=false
