modLoader="javafml"
loaderVersion="[47,)"
license="LGPL"
issueTrackerURL="https://github.com/CinemaMod/mcef/issues"
displayURL="https://github.com/CinemaMod/mcef"
logoFile="icon.png"
# credits=""
authors="ds58"
[[mods]]
modId="mcef"
version="2.1.6-1.20.1"
displayName="MCEF (Minecraft Chromium Embedded Framework)"
updateJSONURL=""
displayTest="NONE"
description='''A Minecraft mod and library for adding the Chromium web browser into the game (Minecraft Chromium Embedded Framework).'''
[[dependencies.mcef]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcef]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.1]"
    ordering="NONE"
    side="BOTH"
