# PacketFixer config for AquaTech (Supports huge FTB Quests sync & custom UI payloads)
allSizesUnlimited=true
forceUnlimitedNbtEnabled=true
packetSize=2147483647
stringSize=2147483647
timeout=300
varInt21=4
varInt=5
chunkPacketData=2147483647
varLong=10
nbtMaxSize=9223372036854775807
decoderSize=2147483647
