"""Строит RodDropTable.java: с каких удочек реально падает каждый ресурс.

    python tools/build_rod_drop_table.py

Источник правды: пулы в FishingLootHandler.rollStarCatcherRodLoot (aquatech_ui). Раньше подсказки к рудам жили в двух
местах (Java и KubeJS) и расходились с настоящими дропами: бамбуковая удочка значилась «2-й». Теперь подсказку
рисует один класс по этой таблице. После правки пулов запусти скрипт заново.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HANDLER = ROOT / "mods" / "aquatech-ui" / "src" / "main" / "java" / "net" / "aquatech" / "ui" / "fishing" / "FishingLootHandler.java"
OUT = ROOT / "mods" / "aquatech-ui" / "src" / "main" / "java" / "net" / "aquatech" / "ui" / "client" / "RodDropTable.java"

TIER_OF = {
    "bamboo_rod": 1, "humble_rod": 2, "good_old_rod": 3, "naturalist_rod": 4, "slimed_rod": 5, "iceborn_rod": 6,
    "starcatcher_rod": 7, "azure_crystal_rod": 8, "sharktooth_rod": 9, "obsidian_rod": 10, "lush_glowberry_rod": 11,
    "magmaforged_rod": 12, "alpha_rod": 13,
}
BONER, SKY = 100, 101


def parse():
    src = HANDLER.read_text(encoding="utf-8")
    start = src.index("private static List<ItemStack> rollStarCatcherRodLoot")
    end = src.index("private static void maybeAdd")
    parts = re.split(r'\n\s*case "([a-z_]+)" ->', src[start:end])
    table = {}
    for i in range(1, len(parts), 2):
        rod, block = parts[i], parts[i + 1]
        tier = TIER_OF.get(rod, BONER if rod == "boner_rod" else SKY if rod == "sky_rod" else None)
        if tier is None:
            continue
        mods = re.findall(r'getModItem\("([^"]+)",\s*Items\.[A-Z_0-9]+', block)
        rest = re.sub(r'getModItem\("[^"]+",\s*Items\.[A-Z_0-9]+', "", block)
        vanilla = ["minecraft:" + name.lower() for name in re.findall(r"new ItemStack\(Items\.([A-Z_0-9]+)", rest)]
        for item in set(mods + vanilla):
            table.setdefault(item, set()).add(tier)
    return table


def render(table):
    lines = [
        "package net.aquatech.ui.client;",
        "",
        "import java.util.HashMap;",
        "import java.util.Map;",
        "",
        "// GENERATED by tools/build_rod_drop_table.py from FishingLootHandler. Do not edit by hand.",
        "",
        "/** С каких удочек падает ресурс: тиры 1..13, 100 это костяная удочка, 101 небесная. */",
        "final class RodDropTable {",
        "",
        "    static final int BONER = 100;",
        "    static final int SKY = 101;",
        "    private static final Map<String, int[]> TIERS = new HashMap<>();",
        "",
        "    static {",
    ]
    for item in sorted(table):
        tiers = ", ".join(str(t) for t in sorted(table[item]))
        lines.append(f'        TIERS.put("{item}", new int[]{{{tiers}}});')
    lines += [
        "    }",
        "",
        "    private RodDropTable() {",
        "    }",
        "",
        "    /** Отсортированные тиры или null, если предмет с удочек не падает. */",
        "    static int[] tiersOf(String itemId) {",
        "        return TIERS.get(itemId);",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def main():
    table = parse()
    OUT.write_text(render(table), encoding="utf-8", newline="")
    print(f"{len(table)} items -> {OUT.name}")


if __name__ == "__main__":
    main()
