# -*- coding: utf-8 -*-
"""Extra workshop quests appended before each chapter's capstone (stable early IDs)."""
from __future__ import annotations

# Local import of q helper shape — keep as plain dicts matching generate_workshop_quests.q()


def q(item, title, sub, reward_item=None, reward_count=1, xp=25):
    return {
        "item": item,
        "title": title,
        "sub": sub,
        "reward_item": reward_item or item,
        "reward_count": reward_count,
        "xp": xp,
    }


# filename -> quests appended after existing chain (keeps WS…0001Q… IDs stable)
EXTRAS: dict[str, list] = {
    "20_ws_bees": [
        q("productivebees:wax", "Воск", "Побочный продукт сот.", "productivebees:wax", 16, 35),
        q("productivebees:wax_block", "Блок воска", "Склад воска.", "productivebees:wax_block", 4, 40),
        q("productivebees:catcher", "Catcher", "Автолов пчёл.", "productivebees:catcher", 1, 55),
        q("productivebees:jar_oak", "Банка пчелы", "Хранение образца.", "productivebees:jar_oak", 2, 45),
        q("productivebees:honeycomb_milky", "Молочные соты", "Линия milky.", "productivebees:honeycomb_milky", 4, 50),
        q("productivebees:honeycomb_ghostly", "Призрачные соты", "Линия ghostly.", "productivebees:honeycomb_ghostly", 4, 55),
        q("productivebees:honeycomb_powdery", "Порошковые соты", "Линия powdery.", "productivebees:honeycomb_powdery", 4, 55),
        q("productivebees:advanced_jungle_beehive", "Тропический улей", "Jungle advanced.", "productivebees:advanced_jungle_beehive", 1, 50),
        q("productivebees:advanced_dark_oak_beehive", "Тёмный улей", "Dark oak advanced.", "productivebees:advanced_dark_oak_beehive", 1, 50),
        q("productivebees:advanced_mangrove_beehive", "Мангровый улей", "Mangrove hive.", "productivebees:advanced_mangrove_beehive", 1, 55),
        q("productivebees:advanced_crimson_beehive", "Багровый улей", "Nether линия.", "productivebees:advanced_crimson_beehive", 1, 60),
        q("productivebees:advanced_warped_beehive", "Искажённый улей", "Warped линия.", "productivebees:advanced_warped_beehive", 1, 60),
        q("productivebees:end_stone_nest", "Гнездо Энда", "Редкий nest.", "productivebees:end_stone_nest", 1, 70),
        q("productivebees:glowstone_nest", "Гнездо свечения", "Glowstone nest.", "productivebees:glowstone_nest", 1, 60),
        q("productivebees:gravel_nest", "Гравийное гнездо", "Дикая линия.", "productivebees:gravel_nest", 1, 45),
        q("productivebees:upgrade_base", "Upgrade Base", "База апгрейдов.", "productivebees:upgrade_base", 2, 50),
        q("productivebees:upgrade_breeding", "Upgrade · Breeding", "Селекция быстрее.", "productivebees:upgrade_breeding", 1, 70),
        q("productivebees:upgrade_filter", "Upgrade · Filter", "Фильтр выхода.", "productivebees:upgrade_filter", 1, 65),
        q("productivebees:upgrade_bee_sampler", "Upgrade · Sampler", "Сэмплер генов.", "productivebees:upgrade_bee_sampler", 1, 75),
        q("productivebees:upgrade_anti_teleport", "Upgrade · Anti-TP", "Пчёлы не телепортятся.", "productivebees:upgrade_anti_teleport", 1, 60),
        q("productivebees:honey_treat_genetic", "Генное лакомство", "Treats под гены.", "productivebees:honey_treat_genetic", 4, 70),
        q("productivebees:amber", "Янтарь роя", "Редкий продукт.", "productivebees:amber", 4, 80),
        q("productivebees:expansion_box_birch", "Expansion Birch", "Расширение birch.", "productivebees:expansion_box_birch", 1, 50),
        q("productivebees:expansion_box_spruce", "Expansion Spruce", "Расширение spruce.", "productivebees:expansion_box_spruce", 1, 50),
        q("minecraft:honeycomb_block", "Блок сот", "Склад сот ванили.", "minecraft:honeycomb_block", 8, 40),
    ],
    "21_ws_roost": [
        q("chicken_roost:chicken_food_tier_2", "Корм T2", "Второй тир рациона.", "chicken_roost:chicken_food_tier_2", 8, 35),
        q("chicken_roost:chicken_food_tier_4", "Корм T4", "Средний+ рацион.", "chicken_roost:chicken_food_tier_4", 8, 45),
        q("chicken_roost:chicken_food_tier_6", "Корм T6", "Высокий рацион.", "chicken_roost:chicken_food_tier_6", 8, 55),
        q("chicken_roost:chicken_food_tier_8", "Корм T8", "Почти максимум.", "chicken_roost:chicken_food_tier_8", 4, 70),
        q("chicken_roost:chicken_essence_tier_2", "Эссенция T2", "Биосинтез tier 2.", "chicken_roost:chicken_essence_tier_2", 4, 35),
        q("chicken_roost:chicken_essence_tier_4", "Эссенция T4", "Биосинтез tier 4.", "chicken_roost:chicken_essence_tier_4", 4, 50),
        q("chicken_roost:chicken_essence_tier_6", "Эссенция T6", "Биосинтез tier 6.", "chicken_roost:chicken_essence_tier_6", 4, 65),
        q("chicken_roost:chicken_essence_tier_8", "Эссенция T8", "Биосинтез tier 8.", "chicken_roost:chicken_essence_tier_8", 2, 80),
        q("chicken_roost:c_coal", "Угольная курица", "Линия угля.", "chicken_roost:c_coal", 1, 45),
        q("chicken_roost:c_iron", "Железная курица", "Линия железа.", "chicken_roost:c_iron", 1, 55),
        q("chicken_roost:c_gold", "Золотая курица", "Линия золота.", "chicken_roost:c_gold", 1, 65),
        q("chicken_roost:c_copper", "Медная курица", "Линия меди.", "chicken_roost:c_copper", 1, 50),
        q("chicken_roost:c_redstone", "Редстоун-курица", "Линия редстоуна.", "chicken_roost:c_redstone", 1, 55),
        q("chicken_roost:c_lapis", "Лазуритовая курица", "Линия лазурита.", "chicken_roost:c_lapis", 1, 60),
        q("chicken_roost:c_quartz", "Кварцевая курица", "Линия кварца.", "chicken_roost:c_quartz", 1, 60),
        q("chicken_roost:c_emerald", "Изумрудная курица", "Линия изумруда.", "chicken_roost:c_emerald", 1, 75),
        q("chicken_roost:c_diamond", "Алмазная курица", "Линия алмаза.", "chicken_roost:c_diamond", 1, 90),
        q("chicken_roost:c_netherite", "Незеритовая курица", "Топ ваниль-линия.", "chicken_roost:c_netherite", 1, 100),
        q("chicken_roost:c_osmium", "Осмиевая курица", "Связка с Mek.", "chicken_roost:c_osmium", 1, 80),
        q("chicken_roost:c_tin", "Оловянная курица", "Сплавы.", "chicken_roost:c_tin", 1, 55),
        q("minecraft:coal", "Уголь с кур", "Топливо фермы.", "minecraft:coal", 32, 40),
        q("minecraft:lapis_lazuli", "Лазурит с кур", "Чары и красители.", "minecraft:lapis_lazuli", 16, 50),
        q("minecraft:quartz", "Кварц с кур", "Под AE2/декор.", "minecraft:quartz", 16, 50),
        q("minecraft:emerald", "Изумруд с кур", "Торговля атолла.", "minecraft:emerald", 8, 70),
        q("minecraft:netherite_scrap", "Незерит-лом с кур", "Путь к слитку.", "minecraft:netherite_scrap", 2, 100),
    ],
    "22_ws_mystical": [
        q("mysticalagriculture:prudentium_seeds", "Семена Prudentium", "Грядка тира 2.", "mysticalagriculture:prudentium_seeds", 2, 50),
        q("mysticalagriculture:tertium_seeds", "Семена Tertium", "Грядка тира 3.", "mysticalagriculture:tertium_seeds", 2, 60),
        q("mysticalagriculture:imperium_seeds", "Семена Imperium", "Грядка тира 4.", "mysticalagriculture:imperium_seeds", 2, 70),
        q("mysticalagriculture:supremium_seeds", "Семена Supremium", "Грядка тира 5.", "mysticalagriculture:supremium_seeds", 2, 85),
        q("mysticalagriculture:iron_seeds", "Семена железа", "Руда с грядки.", "mysticalagriculture:iron_seeds", 2, 55),
        q("mysticalagriculture:gold_seeds", "Семена золота", "Золото с грядки.", "mysticalagriculture:gold_seeds", 2, 65),
        q("mysticalagriculture:diamond_seeds", "Семена алмаза", "Алмаз с грядки.", "mysticalagriculture:diamond_seeds", 1, 90),
        q("mysticalagriculture:redstone_seeds", "Семена редстоуна", "Сигналы с грядки.", "mysticalagriculture:redstone_seeds", 2, 55),
        q("mysticalagriculture:lapis_lazuli_seeds", "Семена лазурита", "Чары с грядки.", "mysticalagriculture:lapis_lazuli_seeds", 2, 55),
        q("mysticalagriculture:copper_seeds", "Семена меди", "Медь с грядки.", "mysticalagriculture:copper_seeds", 2, 50),
        q("mysticalagriculture:coal_seeds", "Семена угля", "Топливо с грядки.", "mysticalagriculture:coal_seeds", 2, 45),
        q("mysticalagriculture:iron_essence", "Эссенция железа", "Крафт слитков.", "mysticalagriculture:iron_essence", 8, 50),
        q("mysticalagriculture:gold_essence", "Эссенция золота", "Крафт слитков.", "mysticalagriculture:gold_essence", 8, 60),
        q("mysticalagriculture:diamond_essence", "Эссенция алмаза", "Крафт алмазов.", "mysticalagriculture:diamond_essence", 4, 85),
        q("mysticalagriculture:prudentium_watering_can", "Лейка Prudentium", "Полив T2.", "mysticalagriculture:prudentium_watering_can", 1, 60),
        q("mysticalagriculture:tertium_watering_can", "Лейка Tertium", "Полив T3.", "mysticalagriculture:tertium_watering_can", 1, 65),
        q("mysticalagriculture:supremium_watering_can", "Лейка Supremium", "Полив T5.", "mysticalagriculture:supremium_watering_can", 1, 90),
        q("mysticalagriculture:awakening_altar", "Awakening Altar", "Алтарь пробуждения.", "mysticalagriculture:awakening_altar", 1, 100),
        q("mysticalagriculture:awakening_pedestal", "Awakening Pedestal", "Пьедестал ритуала.", "mysticalagriculture:awakening_pedestal", 4, 90),
        q("mysticalagriculture:prudentium_furnace", "Печь Prudentium", "Плавка T2.", "mysticalagriculture:prudentium_furnace", 1, 60),
        q("mysticalagriculture:tertium_furnace", "Печь Tertium", "Плавка T3.", "mysticalagriculture:tertium_furnace", 1, 70),
        q("mysticalagriculture:imperium_furnace", "Печь Imperium", "Плавка T4.", "mysticalagriculture:imperium_furnace", 1, 80),
        q("mysticalagriculture:air_seeds", "Семена воздуха", "Стихийная грядка.", "mysticalagriculture:air_seeds", 2, 55),
        q("mysticalagriculture:water_seeds", "Семена воды", "Стихия океана.", "mysticalagriculture:water_seeds", 2, 55),
        q("mysticalagriculture:earth_seeds", "Семена земли", "Стихия атолла.", "mysticalagriculture:earth_seeds", 2, 55),
        q("mysticalagriculture:fire_seeds", "Семена огня", "Стихия жара.", "mysticalagriculture:fire_seeds", 2, 55),
    ],
    "23_ws_create_water": [
        q("create:andesite_alloy", "Андезитовый сплав", "База Create.", "create:andesite_alloy", 16, 30),
        q("create:andesite_casing", "Andesite Casing", "Корпус кинетики.", "create:andesite_casing", 8, 35),
        q("create:shaft", "Вал", "Передача вращения.", "create:shaft", 16, 30),
        q("create:cogwheel", "Шестерня", "Передача.", "create:cogwheel", 8, 30),
        q("create:large_cogwheel", "Большая шестерня", "Редукция.", "create:large_cogwheel", 4, 35),
        q("create:gearbox", "Gearbox", "Поворот вала.", "create:gearbox", 2, 40),
        q("create:clutch", "Clutch", "Сцепление.", "create:clutch", 1, 40),
        q("create:gearshift", "Gearshift", "Реверс.", "create:gearshift", 1, 40),
        q("create:belt_connector", "Ремень", "Логистика предметов.", "create:belt_connector", 8, 35),
        q("create:andesite_funnel", "Funnel", "Ввод/вывод на ленту.", "create:andesite_funnel", 4, 40),
        q("create:chute", "Chute", "Вертикальный сброс.", "create:chute", 4, 35),
        q("create:item_drain", "Item Drain", "Слив жидкостей из предметов.", "create:item_drain", 1, 45),
        q("create:item_vault", "Item Vault", "Склад Create.", "create:item_vault", 2, 50),
        q("create:copper_sheet", "Медный лист", "Листовой металл.", "create:copper_sheet", 8, 35),
        q("create:brass_ingot", "Латунь", "Продвинутый сплав.", "create:brass_ingot", 8, 50),
        q("create:brass_casing", "Brass Casing", "Умные машины.", "create:brass_casing", 4, 55),
        q("create:precision_mechanism", "Precision Mechanism", "Точная механика.", "create:precision_mechanism", 2, 70),
        q("create:electron_tube", "Electron Tube", "Электроника Create.", "create:electron_tube", 4, 55),
        q("create:mechanical_arm", "Mechanical Arm", "Роборука.", "create:mechanical_arm", 1, 80),
        q("create:deployer", "Deployer", "ПКМ-автомат.", "create:deployer", 1, 60),
        q("create:mechanical_press", "Press", "Штамп.", "create:mechanical_press", 1, 55),
        q("create:millstone", "Millstone", "Помол.", "create:millstone", 1, 45),
        q("create:blaze_burner", "Blaze Burner", "Нагрев надпечи.", "create:blaze_burner", 1, 60),
        q("create_aquatic_ambitions:prismarine_rod", "Prismarine Rod", "Стержень аддона.", "create_aquatic_ambitions:prismarine_rod", 4, 55),
        q("minecraft:kelp", "Ламинария", "Водоросли фермы.", "minecraft:kelp", 32, 25),
        q("minecraft:dried_kelp_block", "Блок сушёной ламинарии", "Топливо/склад.", "minecraft:dried_kelp_block", 8, 30),
        q("minecraft:nautilus_shell", "Раковина наутилуса", "Под conduit.", "minecraft:nautilus_shell", 2, 45),
    ],
    "24_ws_atoll_atmosphere": [
        q("quark:bottled_cloud", "Бутылка облака", "QoL Quark.", "quark:bottled_cloud", 2, 35),
        q("quark:feeding_trough", "Кормушка Quark", "Животные у пирса.", "quark:feeding_trough", 1, 40),
        q("quark:grate", "Решётка", "Пол над водой.", "quark:grate", 8, 30),
        q("quark:iron_plate", "Железная плита", "Обшивка цеха.", "quark:iron_plate", 16, 30),
        q("quark:rusty_iron_plate", "Ржавая плита", "Индустриальный декор.", "quark:rusty_iron_plate", 8, 30),
        q("quark:obsidian_pressure_plate", "Обсидиановая плита", "Тяжёлый редстоун.", "quark:obsidian_pressure_plate", 1, 40),
        q("quark:red_corundum", "Корунд", "Кристалл Quark.", "quark:red_corundum", 4, 40),
        q("quark:blue_corundum", "Синий корунд", "Цвет океана.", "quark:blue_corundum", 4, 40),
        q("quark:myalite", "Myalite", "Камень Энда Quark.", "quark:myalite", 8, 45),
        q("quark:duskbound_block", "Duskbound", "Тёмный декор.", "quark:duskbound_block", 8, 40),
        q("quark:blue_blossom_sapling", "Саженец цветения", "Деревья Quark.", "quark:blue_blossom_sapling", 2, 35),
        q("quark:ancient_tome", "Древний том", "Усиление чар.", "quark:ancient_tome", 1, 70),
        q("supplementaries:awning_blue", "Синий навес", "Тень на пирсе.", "supplementaries:awning_blue", 2, 30),
        q("supplementaries:blackboard", "Доска", "Заметки экипажа.", "supplementaries:blackboard", 1, 35),
        q("supplementaries:globe", "Глобус", "Навигация каюты.", "supplementaries:globe", 1, 40),
        q("supplementaries:altimeter", "Высотомер", "QoL высоты.", "supplementaries:altimeter", 1, 35),
        q("supplementaries:bamboo_spikes", "Бамбуковые шипы", "Защита пирса.", "supplementaries:bamboo_spikes", 4, 35),
        q("supplementaries:flint_block", "Блок кремня", "Склад/декор.", "supplementaries:flint_block", 4, 25),
        q("supplementaries:sugar_cube", "Сахарный куб", "Склад сахара.", "supplementaries:sugar_cube", 4, 25),
        q("supplementaries:present", "Подарок", "Упаковка лута.", "supplementaries:present", 2, 30),
        q("supplementaries:safe", "Сейф", "Защищённый склад.", "supplementaries:safe", 1, 55),
        q("supplementaries:lock_block", "Замок-блок", "Контроль доступа.", "supplementaries:lock_block", 1, 45),
        q("supplementaries:key", "Ключ", "К сейфу/замку.", "supplementaries:key", 1, 40),
        q("supplementaries:notice_board", "Доска объявлений", "Квесты экипажа.", "supplementaries:notice_board", 1, 40),
        q("supplementaries:flag_blue", "Синий флаг", "Флаг флота.", "supplementaries:flag_blue", 1, 35),
        q("supplementaries:wind_vane", "Флюгер", "Ветер на мачте.", "supplementaries:wind_vane", 1, 35),
        q("supplementaries:crystal_display", "Crystal Display", "Цифры/декор.", "supplementaries:crystal_display", 1, 45),
        q("minecraft:lantern", "Фонарь", "Свет гавани.", "minecraft:lantern", 8, 20),
        q("minecraft:soul_lantern", "Soul Lantern", "Холодный свет.", "minecraft:soul_lantern", 4, 25),
    ],
    "25_ws_ocean_rituals": [
        q("botania:fertilizer", "Floral Fertilizer", "Краситель цветов Botania.", "botania:fertilizer", 8, 30),
        q("botania:white_mystical_flower", "Белый мистический цветок", "Источник лепестков.", "botania:white_mystical_flower", 4, 30),
        q("botania:blue_mystical_flower", "Синий мистический цветок", "Цвет океана.", "botania:blue_mystical_flower", 4, 30),
        q("botania:cyan_mystical_flower", "Бирюзовый цветок", "Палитра атолла.", "botania:cyan_mystical_flower", 4, 30),
        q("botania:endoflame", "Endoflame", "Генератор маны (уголь).", "botania:endoflame", 1, 50),
        q("botania:hydroangeas", "Hydroangeas", "Мана из воды.", "botania:hydroangeas", 1, 55),
        q("botania:thermalily", "Thermalily", "Мана из лавы.", "botania:thermalily", 1, 60),
        q("botania:rosa_arcana", "Rosa Arcana", "Мана из XP.", "botania:rosa_arcana", 1, 65),
        q("botania:runic_altar", "Runic Altar", "Крафт рун.", "botania:runic_altar", 1, 70),
        q("botania:rune_mana", "Руна маны", "Базовая руна.", "botania:rune_mana", 1, 65),
        q("botania:rune_fire", "Руна огня", "Стихия жара.", "botania:rune_fire", 1, 70),
        q("botania:rune_air", "Руна воздуха", "Стихия ветра.", "botania:rune_air", 1, 70),
        q("botania:terrasteel_ingot", "Terrasteel", "Продвинутый металл.", "botania:terrasteel_ingot", 2, 90),
        q("botania:mana_pylon", "Mana Pylon", "Усиление маны.", "botania:mana_pylon", 1, 75),
        q("botania:alchemy_catalyst", "Alchemy Catalyst", "Алхимия в pool.", "botania:alchemy_catalyst", 1, 80),
        q("ars_nouveau:sourcestone", "Sourcestone", "Блок source.", "ars_nouveau:sourcestone", 16, 45),
        q("ars_nouveau:sourceberry_bush", "Sourceberry", "Ягоды source.", "ars_nouveau:sourceberry_bush", 4, 40),
        q("ars_nouveau:agronomic_sourcelink", "Agronomic Sourcelink", "Source с фермы.", "ars_nouveau:agronomic_sourcelink", 1, 60),
        q("ars_nouveau:volcanic_sourcelink", "Volcanic Sourcelink", "Source с лавы.", "ars_nouveau:volcanic_sourcelink", 1, 65),
        q("ars_nouveau:scribes_table", "Scribe's Table", "Сборка глифов.", "ars_nouveau:scribes_table", 1, 70),
        q("ars_nouveau:blank_glyph", "Blank Glyph", "Пустой глиф.", "ars_nouveau:blank_glyph", 4, 50),
        q("ars_nouveau:blank_parchment", "Blank Parchment", "Свитки.", "ars_nouveau:blank_parchment", 8, 40),
        q("ars_nouveau:magebloom_crop", "Magebloom Crop", "Посев магии.", "ars_nouveau:magebloom_crop", 4, 45),
        q("ars_nouveau:archmage_spell_book", "Книга архимага", "Топ книга заклинаний.", "ars_nouveau:archmage_spell_book", 1, 110),
        q("ars_nouveau:basic_spell_turret", "Spell Turret", "Турель заклинаний.", "ars_nouveau:basic_spell_turret", 1, 85),
        q("ars_nouveau:relay", "Source Relay", "Передача source.", "ars_nouveau:relay", 2, 70),
        q("ars_nouveau:wixie_charm", "Wixie Charm", "Автокрафт Ars.", "ars_nouveau:wixie_charm", 1, 90),
        q("ars_nouveau:starbuncle_charm", "Starbuncle Charm", "Логистика Ars.", "ars_nouveau:starbuncle_charm", 1, 80),
        q("botania:fabulous_pool", "Fabulous Pool", "Красивый пруд маны.", "botania:fabulous_pool", 1, 85),
    ],
    "26_ws_mek": [
        q("mekanism:dust_iron", "Пыль железа", "После crusher.", "mekanism:dust_iron", 16, 35),
        q("mekanism:dust_gold", "Пыль золота", "После crusher.", "mekanism:dust_gold", 8, 40),
        q("mekanism:dust_copper", "Пыль меди", "После crusher.", "mekanism:dust_copper", 16, 35),
        q("mekanism:enriched_iron", "Enriched Iron", "Инфузия стали.", "mekanism:enriched_iron", 8, 45),
        q("mekanism:enriched_redstone", "Enriched Redstone", "Инфузия сплавов.", "mekanism:enriched_redstone", 8, 50),
        q("mekanism:enriched_diamond", "Enriched Diamond", "Высокая инфузия.", "mekanism:enriched_diamond", 4, 70),
        q("mekanism:alloy_reinforced", "Reinforced Alloy", "Сплав T3.", "mekanism:alloy_reinforced", 4, 70),
        q("mekanism:alloy_atomic", "Atomic Alloy", "Сплав T4.", "mekanism:alloy_atomic", 2, 90),
        q("mekanism:advanced_control_circuit", "Advanced Circuit", "Электроника T2.", "mekanism:advanced_control_circuit", 4, 60),
        q("mekanism:ultimate_control_circuit", "Ultimate Circuit", "Электроника T4.", "mekanism:ultimate_control_circuit", 2, 100),
        q("mekanism:precision_sawmill", "Precision Sawmill", "Пилорама Mek.", "mekanism:precision_sawmill", 1, 55),
        q("mekanism:combiner", "Combiner", "Сборка пыли в руду.", "mekanism:combiner", 1, 55),
        q("mekanism:osmium_compressor", "Osmium Compressor", "Сжатие осмием.", "mekanism:osmium_compressor", 1, 65),
        q("mekanism:purification_chamber", "Purification Chamber", "Очистка руд.", "mekanism:purification_chamber", 1, 70),
        q("mekanism:chemical_injection_chamber", "Injection Chamber", "Химинъекция.", "mekanism:chemical_injection_chamber", 1, 80),
        q("mekanism:electrolytic_separator", "Electrolytic Separator", "Вода → газы.", "mekanism:electrolytic_separator", 1, 75),
        q("mekanism:chemical_oxidizer", "Chemical Oxidizer", "Окисление.", "mekanism:chemical_oxidizer", 1, 75),
        q("mekanism:chemical_infuser", "Chemical Infuser", "Смесь газов.", "mekanism:chemical_infuser", 1, 80),
        q("mekanism:basic_chemical_tank", "Chemical Tank", "Хранение газов.", "mekanism:basic_chemical_tank", 1, 60),
        q("mekanism:basic_logistical_transporter", "Logistical Transporter", "Item pipes Mek.", "mekanism:basic_logistical_transporter", 16, 50),
        q("mekanism:basic_mechanical_pipe", "Mechanical Pipe", "Жидкостные трубы.", "mekanism:basic_mechanical_pipe", 16, 50),
        q("mekanism:basic_pressurized_tube", "Pressurized Tube", "Газовые трубы.", "mekanism:basic_pressurized_tube", 16, 55),
        q("mekanism:basic_thermodynamic_conductor", "Thermo Conductor", "Тепло.", "mekanism:basic_thermodynamic_conductor", 8, 55),
        q("mekanism:advanced_energy_cube", "Advanced Energy Cube", "Больший буфер.", "mekanism:advanced_energy_cube", 1, 75),
        q("mekanism:elite_energy_cube", "Elite Energy Cube", "Элитный буфер.", "mekanism:elite_energy_cube", 1, 95),
        q("mekanism:basic_tier_installer", "Tier Installer", "Апгрейд фабрик.", "mekanism:basic_tier_installer", 1, 70),
        q("mekanism:basic_enriching_factory", "Enriching Factory", "Фабрика обогащения.", "mekanism:basic_enriching_factory", 1, 80),
        q("mekanism:basic_smelting_factory", "Smelting Factory", "Фабрика плавки.", "mekanism:basic_smelting_factory", 1, 80),
        q("mekanism:atomic_disassembler", "Atomic Disassembler", "Мультиинструмент.", "mekanism:atomic_disassembler", 1, 110),
        q("mekanism:free_runners", "Free Runners", "Ботинки скорости.", "mekanism:free_runners", 1, 70),
        q("mekanism:jetpack", "Jetpack", "Полёт Mek.", "mekanism:jetpack", 1, 90),
        q("mekanism:scuba_mask", "Scuba Mask", "Дыхание под водой.", "mekanism:scuba_mask", 1, 75),
        q("mekanism:flamethrower", "Flamethrower", "Огнемёт.", "mekanism:flamethrower", 1, 85),
        q("mekanism:configurator", "Configurator", "Настройка сторон.", "mekanism:configurator", 1, 50),
        q("mekanism:dictionary", "Dictionary", "Теги предметов.", "mekanism:dictionary", 1, 40),
        q("mekanism:gauge_dropper", "Gauge Dropper", "Замер газов/жидкостей.", "mekanism:gauge_dropper", 1, 45),
    ],
    "27_ws_ae2": [
        q("ae2:certus_quartz_dust", "Certus Dust", "Пыль кварца.", "ae2:certus_quartz_dust", 16, 30),
        q("ae2:ender_dust", "Ender Dust", "Пыль эндера.", "ae2:ender_dust", 8, 35),
        q("ae2:sky_stone_block", "Sky Stone", "Камень неба.", "ae2:sky_stone_block", 16, 40),
        q("ae2:smooth_sky_stone_block", "Smooth Sky Stone", "Обработанный sky stone.", "ae2:smooth_sky_stone_block", 8, 45),
        q("ae2:quartz_glass", "Quartz Glass", "Стекло AE2.", "ae2:quartz_glass", 8, 40),
        q("ae2:quartz_vibrant_glass", "Vibrant Quartz Glass", "Яркое стекло.", "ae2:quartz_vibrant_glass", 4, 50),
        q("ae2:calculation_processor_press", "Calc Press", "Пресс расчёта.", "ae2:calculation_processor_press", 1, 60),
        q("ae2:logic_processor_press", "Logic Press", "Пресс логики.", "ae2:logic_processor_press", 1, 60),
        q("ae2:engineering_processor_press", "Eng Press", "Пресс инженерии.", "ae2:engineering_processor_press", 1, 65),
        q("ae2:silicon_press", "Silicon Press", "Пресс кремния.", "ae2:silicon_press", 1, 55),
        q("ae2:printed_silicon", "Printed Silicon", "Заготовка чипа.", "ae2:printed_silicon", 8, 45),
        q("ae2:printed_calculation_processor", "Printed Calc", "Заготовка CPU.", "ae2:printed_calculation_processor", 4, 50),
        q("ae2:annihilation_core", "Annihilation Core", "Ядро разрушения.", "ae2:annihilation_core", 2, 55),
        q("ae2:formation_core", "Formation Core", "Ядро создания.", "ae2:formation_core", 2, 55),
        q("ae2:cell_component_16k", "16k Component", "Больше места.", "ae2:cell_component_16k", 1, 75),
        q("ae2:cell_component_64k", "64k Component", "Крупная ячейка.", "ae2:cell_component_64k", 1, 95),
        q("ae2:item_storage_cell_4k", "4k Cell", "Готовая 4k.", "ae2:item_storage_cell_4k", 1, 70),
        q("ae2:fluid_storage_cell_1k", "1k Fluid Cell", "Жидкости в ME.", "ae2:fluid_storage_cell_1k", 1, 65),
        q("ae2:storage_bus", "Storage Bus", "Внешний склад в сети.", "ae2:storage_bus", 1, 60),
        q("ae2:storage_monitor", "Storage Monitor", "Монитор стака.", "ae2:storage_monitor", 1, 55),
        q("ae2:level_emitter", "Level Emitter", "Сигнал по количеству.", "ae2:level_emitter", 1, 55),
        q("ae2:formation_plane", "Formation Plane", "Выкладка в мир.", "ae2:formation_plane", 1, 70),
        q("ae2:annihilation_plane", "Annihilation Plane", "Сбор из мира.", "ae2:annihilation_plane", 1, 70),
        q("ae2:pattern_encoding_terminal", "Pattern Encoding", "Запись паттернов.", "ae2:pattern_encoding_terminal", 1, 80),
        q("ae2:crafting_accelerator", "Crafting Accelerator", "Ускорение CPU.", "ae2:crafting_accelerator", 1, 85),
        q("ae2:1k_crafting_storage", "1k Crafting Storage", "Память автокрафта.", "ae2:1k_crafting_storage", 1, 75),
        q("ae2:crafting_monitor", "Crafting Monitor", "Статус крафта.", "ae2:crafting_monitor", 1, 70),
        q("ae2:wireless_receiver", "Wireless Receiver", "Беспроводка.", "ae2:wireless_receiver", 1, 65),
        q("ae2:wireless_terminal", "Wireless Terminal", "Терминал в кармане.", "ae2:wireless_terminal", 1, 90),
        q("ae2:me_p2p_tunnel", "P2P Tunnel", "Туннель каналов.", "ae2:me_p2p_tunnel", 2, 80),
        q("ae2:quartz_fiber", "Quartz Fiber", "Оптика каналов.", "ae2:quartz_fiber", 8, 45),
        q("ae2:fluix_pearl", "Fluix Pearl", "Жемчуг fluix.", "ae2:fluix_pearl", 4, 60),
        q("ae2:memory_card", "Memory Card", "Копия настроек.", "ae2:memory_card", 1, 50),
        q("ae2:network_tool", "Network Tool", "Диагностика ME.", "ae2:network_tool", 1, 55),
        q("ae2:certus_quartz_wrench", "Certus Wrench", "Ключ AE2.", "ae2:certus_quartz_wrench", 1, 40),
    ],
    "28_ws_thermal": [
        q("minecraft:copper_ingot", "Медь для Thermal", "Базовый металл линии.", "minecraft:copper_ingot", 16, 25),
        q("thermal:constantan_ingot", "Константан", "Сплав Cu+Ni.", "thermal:constantan_ingot", 8, 40),
        q("thermal:tin_dust", "Пыль олова", "Переработка руды.", "thermal:tin_dust", 8, 30),
        q("thermal:lead_dust", "Пыль свинца", "Переработка руды.", "thermal:lead_dust", 8, 30),
        q("thermal:silver_dust", "Пыль серебра", "Переработка руды.", "thermal:silver_dust", 8, 35),
        q("thermal:nickel_dust", "Пыль никеля", "Переработка руды.", "thermal:nickel_dust", 8, 35),
        q("thermal:bronze_gear", "Бронзовая шестерня", "Деталь машин.", "thermal:bronze_gear", 4, 40),
        q("thermal:invar_gear", "Инвар шестерня", "Жаропрочная деталь.", "thermal:invar_gear", 4, 45),
        q("thermal:electrum_gear", "Электрум шестерня", "Проводник.", "thermal:electrum_gear", 4, 50),
        q("thermal:tin_gear", "Оловянная шестерня", "Базовая деталь.", "thermal:tin_gear", 4, 35),
        q("thermal:silver_gear", "Серебряная шестерня", "Деталь машин.", "thermal:silver_gear", 4, 45),
        q("thermal:nickel_gear", "Никелевая шестерня", "Деталь машин.", "thermal:nickel_gear", 4, 45),
        q("thermal:constantan_gear", "Константан шестерня", "Сплавная деталь.", "thermal:constantan_gear", 4, 50),
        q("thermal:bronze_plate", "Бронзовая пластина", "Штамп press.", "thermal:bronze_plate", 8, 40),
        q("thermal:invar_plate", "Инвар пластина", "Штамп press.", "thermal:invar_plate", 4, 45),
        q("thermal:electrum_plate", "Электрум пластина", "Штамп press.", "thermal:electrum_plate", 4, 50),
        q("thermal:constantan_plate", "Константан пластина", "Штамп press.", "thermal:constantan_plate", 4, 45),
        q("thermal:machine_chiller", "Chiller", "Охлаждение.", "thermal:machine_chiller", 1, 65),
        q("thermal:machine_pyrolyzer", "Pyrolyzer", "Пиролиз.", "thermal:machine_pyrolyzer", 1, 70),
        q("thermal:machine_bottler", "Bottler", "Розлив Thermal.", "thermal:machine_bottler", 1, 60),
        q("thermal:machine_brewer", "Brewer", "Зелья/растворы.", "thermal:machine_brewer", 1, 65),
        q("thermal:dynamo_compression", "Compression Dynamo", "Жидкости → RF.", "thermal:dynamo_compression", 1, 65),
        q("thermal:dynamo_numismatic", "Numismatic Dynamo", "Монеты → RF.", "thermal:dynamo_numismatic", 1, 70),
        q("thermal:dynamo_disenchantment", "Disenchant Dynamo", "Чары → RF.", "thermal:dynamo_disenchantment", 1, 75),
        q("thermal:dynamo_gourmand", "Gourmand Dynamo", "Еда → RF.", "thermal:dynamo_gourmand", 1, 60),
        q("thermal:device_tree_extractor", "Tree Extractor", "Сок из деревьев.", "thermal:device_tree_extractor", 1, 55),
        q("thermal:device_nullifier", "Nullifier", "Утиль мусора.", "thermal:device_nullifier", 1, 45),
        q("thermal:device_collector", "Collector", "Сбор дропа.", "thermal:device_collector", 1, 50),
        q("thermal:device_potion_infuser", "Potion Infuser", "Зелья на броню.", "thermal:device_potion_infuser", 1, 60),
        q("thermal:device_hive_extractor", "Hive Extractor", "Мёд из ульев.", "thermal:device_hive_extractor", 1, 55),
        q("thermal:device_fisher", "Aquatic Entangler", "Авторыбалка Thermal.", "thermal:device_fisher", 1, 70),
        q("thermal:device_composter", "Composter", "Компост машина.", "thermal:device_composter", 1, 50),
        q("thermal:device_soil_infuser", "Soil Infuser", "Почва фермы.", "thermal:device_soil_infuser", 1, 55),
        q("thermal:upgrade_augment_1", "Upgrade Augment I", "Апгрейд машин.", "thermal:upgrade_augment_1", 1, 55),
        q("thermal:upgrade_augment_2", "Upgrade Augment II", "Апгрейд II.", "thermal:upgrade_augment_2", 1, 70),
        q("thermal:upgrade_augment_3", "Upgrade Augment III", "Апгрейд III.", "thermal:upgrade_augment_3", 1, 90),
        q("thermal:machine_efficiency_augment", "Efficiency Augment", "Меньше энергии.", "thermal:machine_efficiency_augment", 1, 65),
        q("thermal:machine_speed_augment", "Speed Augment", "Быстрее цикл.", "thermal:machine_speed_augment", 1, 65),
        q("thermal:area_radius_augment", "Radius Augment", "Радиус устройств.", "thermal:area_radius_augment", 1, 60),
        q("thermal:phytogro", "Phyto-Gro", "Удобрение.", "thermal:phytogro", 16, 40),
        q("thermal:slag", "Шлак", "Побочка плавки.", "thermal:slag", 16, 30),
        q("thermal:rosin", "Канифоль", "Побочка деревьев.", "thermal:rosin", 8, 35),
        q("thermal:bitumen", "Битум", "Сырьё нефтехимии.", "thermal:bitumen", 8, 40),
        q("thermal:tar", "Дёготь", "Побочка пиролиза.", "thermal:tar", 8, 40),
        q("thermal:cinnabar", "Кинабарь", "Катализатор.", "thermal:cinnabar", 8, 45),
        q("thermal:niter", "Селитра", "Катализатор.", "thermal:niter", 8, 40),
        q("thermal:apatite", "Апатит", "Катализатор/удобрение.", "thermal:apatite", 8, 40),
        q("thermal:sulfur", "Сера", "Химия Thermal.", "thermal:sulfur", 8, 40),
    ],
    "29_ws_if": [
        q("industrialforegoing:plant_fertilizer", "Plant Fertilizer", "Удобрение грядок IF.", "industrialforegoing:plant_fertilizer", 1, 60),
        q("industrialforegoing:water_condensator", "Water Condensator", "Вода из воздуха.", "industrialforegoing:water_condensator", 1, 50),
        q("industrialforegoing:pitiful_generator", "Pitiful Generator", "Слабый генератор.", "industrialforegoing:pitiful_generator", 1, 45),
        q("industrialforegoing:dissolution_chamber", "Dissolution Chamber", "Пластик и растворы.", "industrialforegoing:dissolution_chamber", 1, 70),
        q("industrialforegoing:latex_bucket", "Ведро латекса", "Жидкий латекс.", "industrialforegoing:latex_bucket", 4, 40),
        q("industrialforegoing:pink_slime", "Pink Slime", "Побочный продукт.", "industrialforegoing:pink_slime", 8, 55),
        q("industrialforegoing:pink_slime_ingot", "Pink Slime Ingot", "Слиток слизи.", "industrialforegoing:pink_slime_ingot", 4, 65),
        q("industrialforegoing:meat_feeder", "Meat Feeder", "Кормление мясом.", "industrialforegoing:meat_feeder", 1, 55),
        q("industrialforegoing:mob_duplicator", "Mob Duplicator", "Копия мобов.", "industrialforegoing:mob_duplicator", 1, 90),
        q("industrialforegoing:mob_imprisonment_tool", "Mob Imprisonment", "Поймай моба.", "industrialforegoing:mob_imprisonment_tool", 1, 60),
        q("industrialforegoing:hydroponic_bed", "Hydroponic Bed", "Гидропоника.", "industrialforegoing:hydroponic_bed", 2, 70),
        q("industrialforegoing:spores_recreator", "Spores Recreator", "Споры/грибы.", "industrialforegoing:spores_recreator", 1, 60),
        q("industrialforegoing:sludge_refiner", "Sludge Refiner", "Переработка шлама.", "industrialforegoing:sludge_refiner", 1, 65),
        q("industrialforegoing:fermentation_station", "Fermentation Station", "Брожение.", "industrialforegoing:fermentation_station", 1, 70),
        q("industrialforegoing:washing_factory", "Washing Factory", "Промывка.", "industrialforegoing:washing_factory", 1, 70),
        q("industrialforegoing:fluid_sieving_machine", "Fluid Sieving", "Просев жидкостей.", "industrialforegoing:fluid_sieving_machine", 1, 75),
        q("industrialforegoing:resourceful_furnace", "Resourceful Furnace", "Печь IF.", "industrialforegoing:resourceful_furnace", 1, 60),
        q("industrialforegoing:material_stonework_factory", "Stonework Factory", "Камень/булыга.", "industrialforegoing:material_stonework_factory", 1, 75),
        q("industrialforegoing:fluid_collector", "Fluid Collector", "Сбор жидкостей.", "industrialforegoing:fluid_collector", 1, 55),
        q("industrialforegoing:fluid_placer", "Fluid Placer", "Разлив жидкостей.", "industrialforegoing:fluid_placer", 1, 55),
        q("industrialforegoing:dye_mixer", "Dye Mixer", "Смесь красителей.", "industrialforegoing:dye_mixer", 1, 50),
        q("industrialforegoing:enchantment_factory", "Enchantment Factory", "Фабрика чар.", "industrialforegoing:enchantment_factory", 1, 90),
        q("industrialforegoing:enchantment_applicator", "Enchant Applicator", "Нанесение чар.", "industrialforegoing:enchantment_applicator", 1, 85),
        q("industrialforegoing:enchantment_extractor", "Enchant Extractor", "Съём чар.", "industrialforegoing:enchantment_extractor", 1, 85),
        q("industrialforegoing:simple_black_hole_unit", "Black Hole Unit", "Компактный склад.", "industrialforegoing:simple_black_hole_unit", 1, 80),
        q("industrialforegoing:black_hole_controller", "Black Hole Controller", "Сеть BH.", "industrialforegoing:black_hole_controller", 1, 95),
        q("industrialforegoing:conveyor", "Conveyor", "Конвейер IF.", "industrialforegoing:conveyor", 16, 45),
        q("industrialforegoing:range_addon_1", "Range Addon", "Радиус машин.", "industrialforegoing:range_addon_1", 1, 50),
        q("industrialforegoing:speed_addon_1", "Speed Addon", "Скорость машин.", "industrialforegoing:speed_addon_1", 1, 55),
        q("industrialforegoing:efficiency_addon_1", "Efficiency Addon", "Экономия энергии.", "industrialforegoing:efficiency_addon_1", 1, 55),
        q("industrialforegoing:processing_addon_1", "Processing Addon", "Больше выхода.", "industrialforegoing:processing_addon_1", 1, 60),
        q("industrialforegoing:laser_lens0", "Laser Lens", "Линза лазера.", "industrialforegoing:laser_lens0", 1, 70),
        q("industrialforegoing:iron_gear", "Iron Gear IF", "Шестерня.", "industrialforegoing:iron_gear", 4, 40),
        q("industrialforegoing:gold_gear", "Gold Gear IF", "Шестерня выше.", "industrialforegoing:gold_gear", 4, 50),
        q("industrialforegoing:diamond_gear", "Diamond Gear IF", "Топ шестерня.", "industrialforegoing:diamond_gear", 2, 70),
    ],
    "2A_ws_apotheosis": [
        q("apotheosis:deepshelf", "Deepshelf", "Глубинная полка.", "apotheosis:deepshelf", 2, 55),
        q("apotheosis:sightshelf", "Sightshelf", "Полка зрения.", "apotheosis:sightshelf", 2, 55),
        q("apotheosis:beeshelf", "Beeshelf", "Пчелиная полка.", "apotheosis:beeshelf", 2, 50),
        q("apotheosis:melonshelf", "Melonshelf", "Арбузная полка.", "apotheosis:melonshelf", 2, 45),
        q("apotheosis:blazing_hellshelf", "Blazing Hellshelf", "Ад++.", "apotheosis:blazing_hellshelf", 1, 70),
        q("apotheosis:crystal_seashelf", "Crystal Seashelf", "Океан++.", "apotheosis:crystal_seashelf", 1, 70),
        q("apotheosis:draconic_endshelf", "Draconic Endshelf", "Энд++.", "apotheosis:draconic_endshelf", 1, 85),
        q("apotheosis:echoing_deepshelf", "Echoing Deepshelf", "Эхо глубин.", "apotheosis:echoing_deepshelf", 1, 80),
        q("apotheosis:filtering_shelf", "Filtering Shelf", "Фильтр чар.", "apotheosis:filtering_shelf", 1, 65),
        q("apotheosis:ender_library", "Ender Library", "Библиотека Энда.", "apotheosis:ender_library", 1, 100),
        q("apotheosis:augmenting_table", "Augmenting Table", "Аугменты.", "apotheosis:augmenting_table", 1, 90),
        q("apotheosis:salvaging_table", "Salvaging Table", "Разбор лута.", "apotheosis:salvaging_table", 1, 80),
        q("apotheosis:gem_cutting_table", "Gem Cutting", "Огранка гемов.", "apotheosis:gem_cutting_table", 1, 85),
        q("apotheosis:gem_dust", "Gem Dust", "Пыль гемов.", "apotheosis:gem_dust", 8, 50),
        q("apotheosis:common_material", "Common Material", "Материал T1.", "apotheosis:common_material", 8, 40),
        q("apotheosis:uncommon_material", "Uncommon Material", "Материал T2.", "apotheosis:uncommon_material", 6, 50),
        q("apotheosis:rare_material", "Rare Material", "Материал T3.", "apotheosis:rare_material", 4, 65),
        q("apotheosis:epic_material", "Epic Material", "Материал T4.", "apotheosis:epic_material", 2, 85),
        q("apotheosis:mythic_material", "Mythic Material", "Материал T5.", "apotheosis:mythic_material", 1, 110),
        q("apotheosis:gem", "Гем Apotheosis", "Сокет-гем.", "apotheosis:gem", 1, 70),
        q("apotheosis:sigil_of_socketing", "Sigil of Socketing", "Сокеты на снаряжении.", "apotheosis:sigil_of_socketing", 1, 80),
        q("apotheosis:sigil_of_withdrawal", "Sigil of Withdrawal", "Съём гемов.", "apotheosis:sigil_of_withdrawal", 1, 75),
        q("apotheosis:sigil_of_rebirth", "Sigil of Rebirth", "Перерождение аффиксов.", "apotheosis:sigil_of_rebirth", 1, 90),
        q("apotheosis:sigil_of_enhancement", "Sigil of Enhancement", "Усиление.", "apotheosis:sigil_of_enhancement", 1, 95),
        q("apotheosis:helmet_tome", "Helmet Tome", "Том шлема.", "apotheosis:helmet_tome", 1, 60),
        q("apotheosis:chestplate_tome", "Chestplate Tome", "Том нагрудника.", "apotheosis:chestplate_tome", 1, 60),
        q("apotheosis:leggings_tome", "Leggings Tome", "Том поножей.", "apotheosis:leggings_tome", 1, 60),
        q("apotheosis:boots_tome", "Boots Tome", "Том ботинок.", "apotheosis:boots_tome", 1, 60),
        q("apotheosis:weapon_tome", "Weapon Tome", "Том оружия.", "apotheosis:weapon_tome", 1, 65),
        q("apotheosis:bow_tome", "Bow Tome", "Том лука.", "apotheosis:bow_tome", 1, 65),
        q("apotheosis:fishing_tome", "Fishing Tome", "Том удочки — тема атолла.", "apotheosis:fishing_tome", 1, 70),
        q("apotheosis:extraction_tome", "Extraction Tome", "Извлечение чар.", "apotheosis:extraction_tome", 1, 75),
        q("apotheosis:improved_scrap_tome", "Improved Scrap Tome", "Лучший разбор.", "apotheosis:improved_scrap_tome", 1, 80),
        q("apotheosis:other_tome", "Other Tome", "Прочие чары.", "apotheosis:other_tome", 1, 60),
        q("minecraft:enchanted_book", "Зачарованная книга", "Носитель чар.", "minecraft:book", 8, 50),
        q("minecraft:netherite_pickaxe", "Незеритовая кирка", "Кандидат под чары.", "minecraft:diamond", 2, 85),
        q("minecraft:netherite_hoe", "Незеритовая мотыга", "Ферма + чары.", "minecraft:netherite_ingot", 1, 80),
        q("minecraft:trident", "Трезубец", "Оружие океана под Apotheosis.", "minecraft:heart_of_the_sea", 1, 90),
    ],
    "2B_ws_enderio": [
        q("enderio:end_steel_ingot", "End Steel", "Сталь Энда.", "enderio:end_steel_ingot", 4, 70),
        q("enderio:construction_alloy_ingot", "Construction Alloy", "Стройсплав.", "enderio:construction_alloy_ingot", 8, 40),
        q("enderio:soularium_nugget", "Soularium Nugget", "Мелочь душ.", "enderio:soularium_nugget", 16, 40),
        q("enderio:pulsating_powder", "Pulsating Powder", "Пульсирующая пыль.", "enderio:pulsating_powder", 8, 45),
        q("enderio:vibrant_powder", "Vibrant Powder", "Яркая пыль.", "enderio:vibrant_powder", 8, 50),
        q("enderio:ender_crystal", "Ender Crystal", "Кристалл эндера.", "enderio:ender_crystal", 2, 70),
        q("enderio:prescient_crystal", "Prescient Crystal", "Кристалл предвидения.", "enderio:prescient_crystal", 2, 80),
        q("enderio:pulsating_crystal", "Pulsating Crystal", "Пульс-кристалл.", "enderio:pulsating_crystal", 2, 70),
        q("enderio:vibrant_crystal", "Vibrant Crystal", "Яркий кристалл.", "enderio:vibrant_crystal", 2, 75),
        q("enderio:z_logic_controller", "Z-Logic Controller", "Логика EIO.", "enderio:z_logic_controller", 1, 80),
        q("enderio:skeletal_contractor", "Skeletal Contractor", "Контрактор скелетов.", "enderio:skeletal_contractor", 1, 85),
        q("enderio:slice_and_splice", "Slice'N'Splice", "Головы/души.", "enderio:slice_and_splice", 1, 85),
        q("enderio:soul_binder", "Soul Binder", "Привязка душ.", "enderio:soul_binder", 1, 90),
        q("enderio:powered_spawner", "Powered Spawner", "Энергоспавнер.", "enderio:powered_spawner", 1, 100),
        q("enderio:impulse_hopper", "Impulse Hopper", "Умная воронка.", "enderio:impulse_hopper", 1, 55),
        q("enderio:crafter", "Crafter EIO", "Автокрафт.", "enderio:crafter", 1, 70),
        q("enderio:painting_machine", "Painting Machine", "Покраска блоков.", "enderio:painting_machine", 1, 55),
        q("enderio:wired_charger", "Wired Charger", "Зарядка предметов.", "enderio:wired_charger", 1, 60),
        q("enderio:drain", "Drain", "Слив жидкостей.", "enderio:drain", 1, 50),
        q("enderio:vacuum_chest", "Vacuum Chest", "Вакуумный сундук.", "enderio:vacuum_chest", 1, 65),
        q("enderio:xp_vacuum", "XP Vacuum", "Сбор XP.", "enderio:xp_vacuum", 1, 60),
        q("enderio:basic_item_filter", "Basic Item Filter", "Фильтр предметов.", "enderio:basic_item_filter", 2, 45),
        q("enderio:advanced_item_filter", "Advanced Item Filter", "Умный фильтр.", "enderio:advanced_item_filter", 1, 60),
        q("enderio:basic_fluid_filter", "Basic Fluid Filter", "Фильтр жидкостей.", "enderio:basic_fluid_filter", 2, 45),
        q("enderio:basic_capacitor_bank", "Basic Capacitor Bank", "Банк энергии.", "enderio:basic_capacitor_bank", 1, 70),
        q("enderio:advanced_capacitor_bank", "Advanced Capacitor Bank", "Большой банк.", "enderio:advanced_capacitor_bank", 1, 90),
        q("enderio:redstone_filter_base", "Redstone Filter Base", "База RS-фильтров.", "enderio:redstone_filter_base", 2, 50),
        q("enderio:conduit_facade", "Conduit Facade", "Маскировка труб.", "enderio:conduit_facade", 8, 45),
        q("enderio:extraction_speed_upgrade_1", "Extraction Speed I", "Быстрее вывод.", "enderio:extraction_speed_upgrade_1", 2, 55),
        q("enderio:extraction_speed_upgrade_2", "Extraction Speed II", "Ещё быстрее.", "enderio:extraction_speed_upgrade_2", 1, 70),
        q("enderio:extraction_speed_upgrade_3", "Extraction Speed III", "Макс вывод.", "enderio:extraction_speed_upgrade_3", 1, 85),
        q("enderio:experience_rod", "Experience Rod", "Стержень XP.", "enderio:experience_rod", 1, 50),
        q("enderio:cold_fire_igniter", "Cold Fire Igniter", "Холодный огонь.", "enderio:cold_fire_igniter", 1, 45),
        q("enderio:coordinate_selector", "Coordinate Selector", "Координаты телепорта.", "enderio:coordinate_selector", 1, 55),
        q("enderio:staff_of_travelling", "Staff of Travelling", "Телепорт-посох.", "enderio:staff_of_travelling", 1, 100),
        q("enderio:dark_steel_sword", "Dark Steel Sword", "Клинок тёмной стали.", "enderio:dark_steel_ingot", 4, 70),
        q("enderio:dark_steel_pickaxe", "Dark Steel Pick", "Кирка тёмной стали.", "enderio:dark_steel_ingot", 4, 70),
    ],
}


def merge_extras(chapters: list[dict]) -> None:
    """Append EXTRAS after each chapter's current quests (stable early IDs)."""
    for ch in chapters:
        extra = EXTRAS.get(ch["filename"])
        if extra:
            ch["quests"].extend(extra)
