# AquaTech: Механизмы
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=aquatech_machines
mod_name=AquaTech: Механизмы
mod_license=All Rights Reserved
mod_version=1.0.1
mod_group_id=net.aquatech.machines
mod_authors=AquaTech
mod_description=Официальные механизмы AquaTech: Рыболов MK-2, Экскаватор, Экстрактор. FE-энергия, авто-выход в сундук.
org.gradle.java.home=C:/Users/xieto/.gradle/jdks/eclipse_adoptium-17-amd64-windows/jdk-17.0.20.1+1
